sudo: required
dist: bionic

language: c

compiler:
  - gcc
python:
  - "3.7"

jobs:
  include:
  - name: "normal"
  - name: "dist"
  - name: "meson"
    addons:
      apt:
        sources:
        - sourceline: 'ppa:kvilhaugsvik/backports'
        packages:
        - meson
        - libtolua-dev

script: "sudo bash ./scripts/travis-build.sh ${TRAVIS_JOB_NAME}"
