name: continuous integration

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  msys2:
    runs-on: windows-2019
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v2
      - name: install dependencies
        uses: msys2/setup-msys2@v2
        with:
          install: >
            make
            gettext
            pkg-config
            git
            automake
            libtool
            autoconf
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-icu
            mingw-w64-x86_64-curl
            mingw-w64-x86_64-bzip2
            mingw-w64-x86_64-readline
            mingw-w64-x86_64-imagemagick
            mingw-w64-x86_64-SDL2_mixer
            mingw-w64-x86_64-drmingw
            mingw-w64-x86_64-tolua
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-SDL2_image
            mingw-w64-x86_64-SDL2_ttf
            mingw-w64-x86_64-SDL2_gfx
            mingw-w64-x86_64-nsis
      - name: build
        shell: msys2 {0}
        run: |
          cd windows/installer_msys2
          make -j$(nproc) snapshot
  os_x:
    runs-on: macos-10.15
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          brew install \
            autoconf \
            automake \
            gettext \
            libtool \
            pkg-config \
            atk \
            freetype \
            gettext \
            glib \
            gtk+3 \
            icu4c \
            pango \
            sdl2_gfx \
            sdl2_image \
            sdl2_mixer \
            sdl2_ttf \
            qt
      - name: build
        shell: bash
        run: ./scripts/travis-build.sh os_x
